"use client";

import { useEffect, useState } from "react";
import { useAuth } from "@/ui/providers/AuthContext";
import { Navbar } from "@/ui/components/layout/Navbar";
import { Button } from "@/ui/components/ui/Button";
import { useParams, useRouter } from "next/navigation";
import Image from "next/image";

export default function DeckViewPage() {
  const { id } = useParams();
  const { user, loading: authLoading } = useAuth();
  const [deck, setDeck] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const router = useRouter();

  useEffect(() => {
    if (!authLoading && !user) {
      router.push("/login");
    }
  }, [user, authLoading, router]);

  useEffect(() => {
    if (user && id) {
      fetch(`/api/game-decks/${id}`)
        .then(res => res.json())
        .then(data => {
            setDeck(data);
        })
        .finally(() => setLoading(false));
    }
  }, [user, id]);

  if (authLoading || loading) return null;
  if (!deck) return <div className="p-20 text-center">Deck not found.</div>;

  return (
    <div className="relative min-h-screen bg-brand-cream flex flex-col pt-32 pb-20">
      <Navbar />
      
      <main className="container mx-auto px-6 grow">
        <header className="mb-12 flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div>
            <div className="inline-block mb-4 px-3 py-1 rounded-full bg-brand-red/10 text-brand-red font-bold text-[10px] tracking-widest uppercase">
              {deck.gameMode?.name || "Standard Mode"}
            </div>
            <h1 className="text-5xl md:text-6xl font-serif font-bold text-brand-brown">{deck.title}</h1>
            <p className="mt-4 text-brand-text-muted font-medium italic text-xl">Rules generated by Sandy.</p>
          </div>
          
          <div className="flex gap-4">
            <Button variant="outline" size="lg" onClick={() => router.push("/decks")}>
              Back to Decks
            </Button>
            <Button 
              variant="primary" 
              size="lg" 
              className="shadow-espresso"
              onClick={() => router.push(`/decks/play/${id}`)}
            >
              Start Game
            </Button>
          </div>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {deck.gameCards?.map((card: any, index: number) => (
            <div key={card.id} className="bg-white p-10 rounded-[40px] shadow-espresso border border-brand-tan/10 relative overflow-hidden group hover:scale-[1.02] transition-all duration-300">
              <div className="absolute top-0 right-0 p-6 font-serif text-4xl text-brand-tan/20 italic group-hover:text-brand-red/20 transition-colors">#{index + 1}</div>
              <p className="text-2xl font-serif font-bold text-brand-brown leading-relaxed relative z-10">{card.ruleText}</p>
              <div className="mt-10 pt-6 border-t border-brand-tan/10 text-[10px] font-bold uppercase tracking-widest text-brand-text-muted">Sandy says...</div>
            </div>
          ))}
        </div>
      </main>

      {/* Decorative Branding */}
      <div className="fixed bottom-10 left-10 pointer-events-none opacity-10 select-none -rotate-12">
        <div className="font-script text-8xl text-brand-brown">No secrets safe.</div>
      </div>
    </div>
  );
}
